CREATE TABLE IF NOT EXISTS meta (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS accounts (id TEXT PRIMARY KEY, label TEXT NOT NULL, adapter TEXT NOT NULL, state TEXT NOT NULL, version INTEGER NOT NULL, secret TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS agents (id TEXT PRIMARY KEY, label TEXT NOT NULL, verifier TEXT NOT NULL UNIQUE, expires INTEGER NOT NULL, revoked INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS grants (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL REFERENCES agents(id), account_id TEXT NOT NULL REFERENCES accounts(id), version INTEGER NOT NULL, revoked INTEGER NOT NULL DEFAULT 0, config TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS requests (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, account_id TEXT NOT NULL, grant_id TEXT NOT NULL, policy_version INTEGER NOT NULL, account_version INTEGER NOT NULL, idem TEXT NOT NULL, hash TEXT NOT NULL, reason TEXT NOT NULL, status TEXT NOT NULL, deadline INTEGER NOT NULL, session_id TEXT, code TEXT, UNIQUE(agent_id,idem));
CREATE TABLE IF NOT EXISTS audit (id INTEGER PRIMARY KEY AUTOINCREMENT, time INTEGER NOT NULL, event TEXT NOT NULL, actor TEXT NOT NULL, target TEXT, code TEXT, duration_ms INTEGER);
CREATE INDEX IF NOT EXISTS audit_time ON audit(time);
PRAGMA user_version = 1;
